### ISSUE TITLE
Error on first install

### ISSUE THREAD

**Issue by alain-andre** [ellefsen/wordpress-heroku-php#13]
Hi there,  thanks for this awesome work.

I'm having an issue after I followed the install steps, Heroku log gives me : 

`[04-Aug-2017 09:54:28 Europe/Oslo] PHP Fatal error:  Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at /app/public/../.env. in /app/vendor/vlucas/phpdotenv/src/Loader.php:75` 

I don't understand why it's looking for a `.env` file if it's *gitignored* and that my Heroku Environment variables have the **CLEARDB_DATABASE_URL** set.

Can anyone help me ?

**Comment by ellefsen** [comment]
The Dotenv library is just for managing your local environment configuration. You don't want that in source control. Just make an empty .env file and I think you'll be fine. The library was added through a pull request that I didn't test properly. I'll try to update the docs and make sure everything runs smoothly. The Foreman setup is no longer recommended either, so I have a few things to update. Sorry about that.

**Comment by alain-andre** [comment]
OK, I see. I'll give it a try.

You say `The Foreman setup is no longer recommended either`, what do you mean ? Do you have some link about that ?

**Comment by ellefsen** [comment]
They recommend using Heroku Local. More about that here: [https://devcenter.heroku.com/articles/heroku-local](https://devcenter.heroku.com/articles/heroku-local)

> As an alternative to using Heroku Local, you can still use Foreman to run your app locally. It’s not officially supported but if you want to use it, you can get more information…
