### ISSUE TITLE
How to add plugins and themes?

### ISSUE THREAD

**Issue by jcguarinpenaranda** [ellefsen/wordpress-heroku-php#15]
Hello, I just deployed an app with this Heroku button and now I'm trying to install plugins and themes.

However, when I `heroku git:clone -a my-app`, the Heroku CLI tells me that it appears that I have cloned an empty repository. My attempt here was to clone the heroku repository and add my theme in the Wordpress configuration, but it seems to be that is not the way.

Please help me solve this :) ty

**Comment by jsdevjournal** [comment]
@jcguarinpenaranda 

What you have to do is to clone this repo instead of from heroku.

`git clone https://github.com/ellefsen/wordpress-heroku-php`

Then you can add a heroku remote git to your local repo

`git remote add heroku https://git.heroku.com/your-app.git`

Then push your local into heroku repo

**Comment by jcguarinpenaranda** [comment]
Thank you so much :)

El 30/03/2018 6:45 a. m., "durunvo" <notifications@github.com> escribió:

@jcguarinpenaranda <https://github.com/jcguarinpenaranda>

What you have to do is to clone this repo instead of from heroku.

git clone https://github.com/ellefsen/wordpress-heroku-php

Then you can add a heroku remote git to your local repo

git remote add heroku https://git.heroku.com/your-app.git

Then push your local into heroku repo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ellefsen/wordpress-heroku-php/issues/15#issuecomment-377508093>,
or mute the thread
