### ISSUE TITLE
Compatibility with php-fpm7.0  ?

### ISSUE THREAD

**Issue by kirylrb** [ellefsen/wordpress-heroku-php#6]
When I try to run foreman for local instanse I got:

```
'02:04:59 web.1  | started with pid 21960
02:04:59 web.1  | Usage: /etc/init.d/php-fpm7.0 {start|stop|status|restart|reload|force-reload}
02:04:59 web.1  | This program requires PHP 5.5.11 or newer; check your 'php-fpm' command.
02:04:59 web.1  | exited with code 1
02:04:59 system | sending SIGTERM to all processes
```

**Comment by ellefsen** [comment]
What version of PHP are you running on your command line? Try running `php -v` and make sure it reads PHP 7.0 or higher. If not then you need to install PHP 7 with Homebrew and update your bash env to include the correct PHP bin in your $PATH.

**Comment by kirylrb** [comment]
`PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
`
